export enum LocationActionTypes {
  GET_LOCATION_BY_CITY_NAME = '[LOCATION] TRIGGER GET LOCATION',
  GET_LOCATION_BY_CITY_NAME_SUCCESS = '[LOCATION] GET LOCATION SUCCESS',
  GET_LOCATION_BY_CITY_NAME_FAILURE = '[LOCATION] GET LOCATION FAILURE',
}
