export enum WeatherActionTypes {
  GET_WEATHER = '[LOCATION] TRIGGER GET WEATHER',
  GET_WEATHER_SUCCESS = '[LOCATION] GET WEATHER SUCCESS',
  GET_WEATHER_FAILURE = '[LOCATION] GET WEATHER FAILURE',
}
